# Script adapted from https://github.com/circuitikz/circuitikz/blob/master/.travis.yml

language: R
sudo: false
cache: packages
warnings_are_errors: false
before_install:
    - tlmgr update --self
    - tlmgr install beamer tools bibunits xcolor geometry
install: echo Installation step # Do not remove this line!
script:
    - mkdir build
    - pdflatex -interaction=nonstopmode -halt-on-error -output-directory build /tex/template.tex
