install:
 - source ./travis/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
    - pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build template.tex
